"""Measure installed CS2 Mirage source geometry, indexed draw calls and triggers.

Reads temporary Source2Viewer exports; never modifies the installed game.
No manually positioned map objects are generated by this script.
"""
from pathlib import Path
from collections import Counter
import argparse
import hashlib
import json
import math
import os
import re
import struct
import tempfile
from itertools import permutations
import numpy as np
from scipy.spatial import ConvexHull, cKDTree
from scipy.spatial.transform import Rotation
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import connected_components
from scipy.sparse.csgraph import dijkstra
from shapely.geometry import Polygon

ROOT = Path(__file__).resolve().parents[1]
TEMP = Path(os.environ.get('CS25D_MAP_SOURCE_DIR',Path(tempfile.gettempdir())/'cs25d-map-tools'))
OFFSET = np.array([17.018, 6.5024, -21.5138])
UNIT = .0254
KEYWORDS = ('ammo_pallet','bomb_tank','shipping_crate','food_crate','wood_pallet',
            'box','barrel','van','car','bus','bench','scaffold','cannon','cart','tarp')


def source_to_game(value):
    v=np.asarray(value,dtype=float)
    return np.array([(v[0]+670)*UNIT,(v[2]+256)*UNIT,(-v[1]-847)*UNIT])


def glb_to_game(vertices):
    v=np.asarray(vertices)
    return v[:,[2,1,0]] * np.array([1,1,-1]) + OFFSET


def game_to_source(vertices):
    v=np.asarray(vertices)
    return np.column_stack((v[:,0]/UNIT-670,-v[:,2]/UNIT-847,v[:,1]/UNIT-256))


class GLB:
    def __init__(self,path):
        self.path=Path(path)
        self.raw=self.path.read_bytes()
        length,kind=struct.unpack_from('<II',self.raw,12)
        assert kind==0x4e4f534a
        self.j=json.loads(self.raw[20:20+length])
        self.binary_offset=20+length+8
        self.parents={child:i for i,node in enumerate(self.j['nodes']) for child in node.get('children',[])}
        self.cache={}
        self.transforms={}

    def accessor(self,index):
        if index in self.cache:return self.cache[index]
        a=self.j['accessors'][index]
        bv=self.j['bufferViews'][a['bufferView']]
        dtype={5120:'i1',5121:'u1',5122:'<i2',5123:'<u2',5125:'<u4',5126:'<f4'}[a['componentType']]
        size={'SCALAR':1,'VEC2':2,'VEC3':3,'VEC4':4,'MAT4':16}[a['type']]
        width=np.dtype(dtype).itemsize
        offset=self.binary_offset+bv.get('byteOffset',0)+a.get('byteOffset',0)
        arr=np.ndarray((a['count'],size),dtype=dtype,buffer=self.raw,offset=offset,strides=(bv.get('byteStride',width*size),width))
        self.cache[index]=arr
        return arr

    def matrix(self,index):
        if index in self.transforms:return self.transforms[index]
        n=self.j['nodes'][index]
        if 'matrix' in n: m=np.array(n['matrix']).reshape(4,4).T
        else:
            m=np.eye(4)
            m[:3,:3]=Rotation.from_quat(n.get('rotation',[0,0,0,1])).as_matrix()@np.diag(n.get('scale',[1,1,1]))
            m[:3,3]=n.get('translation',[0,0,0])
        if index in self.parents:m=self.matrix(self.parents[index])@m
        self.transforms[index]=m
        return m

    def geometry(self,index,source_space=True):
        node=self.j['nodes'][index]
        if 'mesh' not in node:return None
        pieces=[]; triangle_count=0
        for primitive in self.j['meshes'][node['mesh']]['primitives']:
            if 'POSITION' not in primitive.get('attributes',{}):continue
            vertices=self.accessor(primitive['attributes']['POSITION'])
            if 'indices' in primitive:
                faces=self.accessor(primitive['indices']).reshape(-1)
                # Aggregate mesh POSITION accessors intentionally contain vertices
                # belonging to other draw calls. Only referenced indices count.
                vertices=vertices[np.unique(faces)]
                triangle_count+=len(faces)//3
            else:triangle_count+=len(vertices)//3
            pieces.append(vertices)
        if not pieces:return None
        vertices=np.concatenate(pieces)
        matrix=self.matrix(index)
        world=vertices@matrix[:3,:3].T+matrix[:3,3]
        return (glb_to_game(world) if source_space else world),triangle_count

    def triangles(self,index,source_space=True):
        node=self.j['nodes'][index]
        if 'mesh' not in node:return np.empty((0,3,3))
        result=[];m=self.matrix(index)
        for p in self.j['meshes'][node['mesh']]['primitives']:
            v=self.accessor(p['attributes']['POSITION'])
            f=self.accessor(p['indices']).reshape(-1) if 'indices' in p else np.arange(len(v))
            points=v[f]@m[:3,:3].T+m[:3,3]
            if source_space:points=glb_to_game(points)
            result.append(points.reshape(-1,3,3))
        return np.concatenate(result)

    def components(self,index):
        """Connected collision shells: inspect actual convex hulls, not aggregate AABBs."""
        node=self.j['nodes'][index]
        if 'mesh' not in node:return []
        verts=[];faces=[];offset=0
        for p in self.j['meshes'][node['mesh']]['primitives']:
            v=self.accessor(p['attributes']['POSITION'])
            ids=self.accessor(p['indices']).reshape(-1) if 'indices' in p else np.arange(len(v))
            unique,inverse=np.unique(ids,return_inverse=True)
            verts.append(v[unique]);faces.append(inverse.reshape(-1,3)+offset);offset+=len(unique)
        v=np.concatenate(verts);f=np.concatenate(faces)
        m=self.matrix(index)
        points=glb_to_game(v@m[:3,:3].T+m[:3,3])
        welded,remap=np.unique(points.round(5),axis=0,return_inverse=True)
        f=remap[f]
        edges=np.concatenate((f[:,[0,1]],f[:,[1,2]],f[:,[2,0]]))
        graph=coo_matrix((np.ones(len(edges),dtype=np.uint8),(edges[:,0],edges[:,1])),shape=(len(welded),len(welded))).tocsr()
        count,labels=connected_components(graph,directed=False)
        order=np.argsort(labels,kind='stable')
        cuts=np.flatnonzero(np.diff(labels[order]))+1
        return [welded[part] for part in np.split(order,cuts) if len(part)>=4]


def read_entities(path):
    text=Path(path).read_text(encoding='utf8')
    result=[]
    for found in re.finditer(r'====(\d+)====\s*\n(.*?)(?=\n====\d+====|\Z)',text,re.S):
        record={'entity_index':int(found.group(1))}
        for line in found.group(2).splitlines():
            m=re.match(r'([\w]+)\s+(.+)$',line.strip())
            if not m:continue
            k,v=m.groups()
            if v.startswith('resource_name:'):v=v.split(':',1)[1]
            try:v=json.loads(v)
            except ValueError:pass
            record[k]=v
        if 'origin' in record:record['position_godot']=source_to_game(record['origin']).round(6).tolist()
        result.append(record)
    return result


def footprint(points):
    xy=np.unique(points[:,[0,2]].round(6),axis=0)
    if len(xy)<3:return {'polygon_xz':xy.tolist()}
    try:hull=xy[ConvexHull(xy).vertices]
    except Exception:return {'polygon_xz':xy.tolist()[:2]}
    vectors=np.roll(hull,-1,axis=0)-hull
    angles=np.unique(np.mod(np.arctan2(vectors[:,1],vectors[:,0]),math.pi/2).round(8))
    best=None
    for angle in angles:
        c,s=math.cos(angle),math.sin(angle)
        rot=np.array([[c,-s],[s,c]])
        rotated=hull@rot
        mn,mx=rotated.min(axis=0),rotated.max(axis=0)
        area=np.prod(mx-mn)
        if best is None or area<best[0]:best=(area,angle,mn,mx,rot)
    area,angle,mn,mx,rot=best
    center=((mn+mx)/2)@rot.T
    return {'polygon_xz':hull.round(6).tolist(),'obb_center_xz':center.round(6).tolist(),
            'obb_extents_xz':(mx-mn).round(6).tolist(),'obb_yaw_rad':round(float(angle),8),
            'footprint_convex_area_m2':round(float(ConvexHull(xy).volume),6)}


def bounds_record(glb,index,with_footprint=False):
    data=glb.geometry(index)
    if data is None:return None
    points,tris=data
    mn,mx=points.min(axis=0),points.max(axis=0)
    center=(mn+mx)/2
    n=glb.j['nodes'][index]
    rec={'node_index':index,'name':n.get('name',''),'mesh_index':n['mesh'],
         'triangles':tris,'bounds_min_godot':mn.round(6).tolist(),'bounds_max_godot':mx.round(6).tolist(),
         'aabb_center_godot':center.round(6).tolist(),'aabb_extents_m':(mx-mn).round(6).tolist(),
         'aabb_center_source_units':game_to_source(center[None,:])[0].round(4).tolist(),
         'world_matrix_glb_column_major':glb.matrix(index).T.ravel().round(9).tolist(),
         'extras':n.get('extras',{})}
    if with_footprint:rec.update(footprint(points))
    return rec


def classify_collision(name,extras):
    flags=extras.get('InteractAs',[])
    if name.startswith(('func_bomb_target','func_buyzone','env_cs_place','post_processing_volume','func_nav_markup','trigger_')):
        return dict(role='trigger_or_metadata',movement=False,bullets=False,vision=False,grenades=False)
    if name.startswith('func_clip_vphysics'):
        return dict(role='physics_object_clip',movement=False,bullets=False,vision=False,grenades=True)
    if 'csgo_grenadeclip' in flags:
        return dict(role='grenade_clip',movement=False,bullets=False,vision=False,grenades=True)
    if 'playerclip' in flags or 'npcclip' in flags:
        return dict(role='player_clip',movement=True,bullets=False,vision=False,grenades=False)
    if 'passbullets' in flags:
        return dict(role='pass_bullets_surface',movement=True,bullets=False,vision=False,grenades=True)
    if 'sky' in flags:
        return dict(role='sky_boundary',movement=True,bullets=True,vision=False,grenades=True)
    return dict(role='solid_surface',movement=True,bullets=True,vision=True,grenades=True)


def cover_clusters(components):
    """Union overlapping source collision footprints, retaining component IDs.

    This is an audit grouping only. It does not create replacement box colliders.
    """
    surfaces={'wood_plank','solidmetal','metal_barrel','wood_panel','wood_solid','rock'}
    source=[]
    for c in components:
        center=c['aabb_center_godot'];size=c['aabb_extents_m']
        if c['surface'] not in surfaces or max(size)>4.5 or size[1]>4.5:continue
        if not (-12<center[0]<25 and 20<center[2]<44 and 1.8<center[1]<6):continue
        poly=Polygon(c['polygon_xz'])
        if poly.area<.025:continue
        source.append((c,poly))
    parent=list(range(len(source)))
    def find(i):
        while parent[i]!=i:parent[i]=parent[parent[i]];i=parent[i]
        return i
    for i,(_,poly) in enumerate(source):
        for j in range(i):
            if poly.distance(source[j][1])<.025:parent[find(i)]=find(j)
    groups={}
    for i,(c,p) in enumerate(source):groups.setdefault(find(i),[]).append(c)
    result=[]
    for group in groups.values():
        if len(group)<2:continue
        mn=np.min([c['bounds_min_godot'] for c in group],axis=0)
        mx=np.max([c['bounds_max_godot'] for c in group],axis=0)
        if max(mx-mn)>7:continue
        result.append({'aabb_center_godot':((mn+mx)/2).round(5).tolist(),'bounds_min_godot':mn.round(5).tolist(),'bounds_max_godot':mx.round(5).tolist(),'aabb_extents_m':(mx-mn).round(5).tolist(),
                       'surfaces':dict(Counter(c['surface'] for c in group)),
                       'components':[[c['world_physics_node'],c['component_index']] for c in group]})
    return sorted(result,key=lambda c:c['aabb_center_godot'][0])


def apply_entity_states(entities,render_glb,physics_glb,renderables,physics_records):
    """Source entity activation is distinct from the model's collision payload.

    Retake brushes are exported even when StartDisabled. Some decorative dynamic
    models also export physics despite solid=0. Match class/model plus the native
    artist pivot before deciding which shapes are active in ordinary bomb mode.
    """
    records=[];disabled_physics=[];nonsolid_physics=[];disabled_render=[]
    disabled_brush=[];never_solid_brush=[];dynamic_nonsolid=[]
    for rec in physics_records:
        classname=rec['name']
        if classname not in ('func_brush','prop_dynamic','prop_dynamic_override'):continue
        pos=glb_to_game(physics_glb.matrix(rec['node_index'])[:3,3][None,:])[0]
        candidates=[e for e in entities if e.get('classname')==classname and 'origin' in e]
        if not candidates:continue
        entity=min(candidates,key=lambda e:np.linalg.norm(np.asarray(e['position_godot'])-pos))
        error=float(np.linalg.norm(np.asarray(entity['position_godot'])-pos))
        assert error<.0001,(rec['node_index'],classname,error)
        disabled=entity.get('startdisabled') is True
        never=(classname=='func_brush' and str(entity.get('solidity'))=='1')
        dynamic=(classname.startswith('prop_dynamic') and str(entity.get('solid'))=='0')
        state={'physics_node_index':rec['node_index'],'entity_index':entity['entity_index'],
               'classname':classname,'model':entity.get('model'),'targetname':entity.get('targetname'),
               'startdisabled':disabled,'solidity':entity.get('solidity'),'solid':entity.get('solid'),
               'origin_match_error_m':error,'active_collision':not(disabled or never or dynamic)}
        rec['entity_state']=state
        if disabled:
            disabled_physics.append(rec['node_index'])
            if classname=='func_brush':disabled_brush.append(rec['node_index'])
        elif never or dynamic:nonsolid_physics.append(rec['node_index'])
        if never and not disabled:never_solid_brush.append(rec['node_index'])
        if dynamic:dynamic_nonsolid.append(rec['node_index'])
        if disabled or never or dynamic:
            rec['collision_policy']={'role':'disabled_entity' if disabled else 'nonsolid_entity',
                                     'movement':False,'bullets':False,'vision':False,'grenades':False}
        records.append(state)
    for entity in entities:
        if not entity.get('startdisabled') or not entity.get('model'):continue
        stem=Path(entity['model']).stem
        for rec in renderables:
            if not rec['name'].startswith(stem+'.'):continue
            pos=glb_to_game(render_glb.matrix(rec['node_index'])[:3,3][None,:])[0]
            error=float(np.linalg.norm(np.asarray(entity['position_godot'])-pos))
            if error>.0001:continue
            rec['entity_state']={'entity_index':entity['entity_index'],'startdisabled':True,
                                 'origin_match_error_m':error,'model':entity['model'],'active_render':False}
            disabled_render.append(rec['node_index'])
    return {'runtime_entity_state':records,'runtime_disabled_render_nodes':disabled_render,
            'runtime_disabled_physics_nodes':disabled_physics,'runtime_nonsolid_physics_nodes':nonsolid_physics,
            'runtime_disabled_brush_physics_nodes':disabled_brush,'runtime_never_solid_brush_physics_nodes':never_solid_brush,
            'runtime_dynamic_nonsolid_physics_nodes':dynamic_nonsolid}


def audit_baked_output(reference,tmp):
    """Independent checks against the actual shipped GLB and native collision text.

    Renderer manifests identify each retained primitive, but positions are read
    again from the source file and compared to vertices in the shipped artifact.
    Collision validation compares every source triangle, including clip layers.
    """
    manifest_path=ROOT/'assets/map/source_geometry_manifest.json'
    output_path=ROOT/'assets/map/source_environment.glb'
    scene_path=ROOT/'assets/map/mirage_baked.tscn'
    if not all(p.exists() for p in [manifest_path,output_path,scene_path]):return {'status':'awaiting_baked_artifacts'}
    manifest=json.loads(manifest_path.read_text(encoding='utf8'))
    source=GLB(tmp/'source_world_materials.glb');baked=GLB(output_path)
    all_points=[];output_triangles=0
    for ni in range(len(baked.j['nodes'])):
        geo=baked.geometry(ni,source_space=False)
        if geo is not None:all_points.append(geo[0]);output_triangles+=geo[1]
    points=np.unique(np.concatenate(all_points),axis=0)
    tree=cKDTree(points)
    opaque_families={'Architecture','Ground','Props','PropsMetal','Glass','Canopy'}
    rows=[];all_preserved=True;source_vertices=0;vertex_missing=0;max_error=0.;alpha_changes=[]
    keyword_report={}
    for key in ('ammo_pallet','bomb_tanks','dust_shipping_crate','aztec_scaffolding','bomb_site_tarp','bucket_tools'):
        original=[r for r in reference['renderables'] if key in r['name']]
        retained=[o for o in manifest['objects'] if key in o['node']]
        keyword_report[key]={'source_draw_calls':len(original),'retained_draw_calls':len(retained),
                             'source_triangles':sum(r['triangles'] for r in original),
                             'output_triangles':sum(r['triangles'] for r in retained)}
        if len(original)!=len(retained):all_preserved=False
    for obj in manifest['objects']:
        ni=obj['node_index'];pi=obj['primitive_index'];node=source.j['nodes'][ni]
        assert node.get('name')==obj['node'],f'Source node mismatch: {ni}'
        primitive=source.j['meshes'][node['mesh']]['primitives'][pi]
        material=source.j['materials'][primitive.get('material',0)]
        alpha_mode=material.get('alphaMode','OPAQUE')
        v=source.accessor(primitive['attributes']['POSITION'])
        ids=source.accessor(primitive['indices']).reshape(-1)
        m=source.matrix(ni)
        v=glb_to_game(v[np.unique(ids)]@m[:3,:3].T+m[:3,3])
        source_bounds=np.array([v.min(axis=0),v.max(axis=0)])
        output_bounds=np.asarray(obj['output_bounds'])
        row={'node_index':ni,'primitive_index':pi,'name':obj['node'],'family':obj['group'],'source_alpha_mode':alpha_mode,
             'source_bounds':source_bounds.round(6).tolist(),'output_bounds':output_bounds.tolist(),
             'max_bounds_delta_m':float(np.max(np.abs(source_bounds-output_bounds))),
             'center_delta_m':float(np.linalg.norm(source_bounds.mean(axis=0)-output_bounds.mean(axis=0)))}
        if obj['group'] in opaque_families and alpha_mode=='OPAQUE':
            errors,_=tree.query(v)
            missing=int(np.count_nonzero(errors>2e-5));error=float(errors.max())
            row.update({'vertex_count':len(v),'max_vertex_error_m':error,'missing_vertices_at_20_micrometres':missing,
                        'triangle_count_unchanged':obj['source_triangles']==obj['triangles']})
            source_vertices+=len(v);vertex_missing+=missing;max_error=max(error,max_error)
            if missing or not row['triangle_count_unchanged']:all_preserved=False
        elif alpha_mode!='OPAQUE' and obj['source_triangles']!=obj['triangles']:
            alpha_changes.append({'node_index':ni,'material':material.get('name'),
                                  'group':obj['group'],'source_triangles':obj['source_triangles'],
                                  'output_triangles':obj['triangles']})
        rows.append(row)
    disabled_render_leaks=sorted(set(reference.get('runtime_disabled_render_nodes',[])) & {o['node_index'] for o in manifest['objects']})
    if disabled_render_leaks:all_preserved=False
    # VRF omits alphaMode for Source animated effects. Verify intentional dust
    # sheet exclusions against original shader metadata rather than treating
    # every glTF-default OPAQUE primitive as solid architecture.
    effects=manifest.get('excluded_shader_effects',[])
    retained_ids={(o['node_index'],o['primitive_index']) for o in manifest['objects']}
    effect_checks=[]
    for effect in effects:
        ni=effect['node_index'];pi=effect['primitive_index'];node=source.j['nodes'][ni]
        primitive=source.j['meshes'][node['mesh']]['primitives'][pi]
        material=source.j['materials'][primitive.get('material',0)]
        vmat=material.get('extras',{}).get('vmat',{})
        valid=material.get('name')=='dust_002' and vmat.get('ShaderName')=='csgo_effects.vfx' and vmat.get('IntParams',{}).get('F_DO_NOT_CAST_SHADOWS')==1 and vmat.get('IntParams',{}).get('F_DEPTH_FEATHER')==1 and (ni,pi) not in retained_ids
        effect_checks.append({**effect,'source_metadata_verified':valid})
        if not valid:all_preserved=False

    # Parse shape arrays and transforms directly; do not trust the collision manifest.
    text=scene_path.read_text(encoding='utf8')
    shape_arrays={int(i):np.fromstring(raw,sep=',').reshape(-1,3,3) for i,raw in re.findall(
        r'\[sub_resource type="ConcavePolygonShape3D" id="Collision(\d+)"\]\s*data = PackedVector3Array\(([^)]*)\)',text)}
    actual_by_layer={1:[],4:[],8:[]}
    for idx,block in re.findall(r'\[node name="WorldCollision(\d+)" type="StaticBody3D"[^\]]*\]([^\[]*)',text):
        pos=np.fromstring(re.search(r'position = Vector3\(([^)]*)\)',block).group(1),sep=',')
        layer=int(re.search(r'collision_layer = (\d+)',block).group(1))
        actual_by_layer[layer].append(shape_arrays[int(idx)]+pos)
    actual_by_layer={k:np.concatenate(v) for k,v in actual_by_layer.items() if v}
    expected_by_layer={1:[],4:[],8:[]};surface_counts=Counter();excluded=Counter();degenerate=0
    for filename,records in [('world_solidphysics_physics.glb',reference['world_physics']),('source_world_physics.glb',reference['entity_physics'])]:
        g=GLB(tmp/filename)
        for rec in records:
            policy=rec['collision_policy']
            if not policy['movement'] and not policy['grenades']:
                excluded[rec['name']]+=1;continue
            layer=(1 if policy['bullets'] else 4) if policy['movement'] else 8
            tri=g.triangles(rec['node_index'])
            good=np.linalg.norm(np.cross(tri[:,1]-tri[:,0],tri[:,2]-tri[:,0]),axis=1)>1e-8
            degenerate+=int(np.count_nonzero(~good));tri=tri[good]
            expected_by_layer[layer].append(tri);surface_counts[policy['role']]+=len(tri)
    collision_rows=[]
    for layer,parts in expected_by_layer.items():
        expected=np.concatenate(parts);actual=actual_by_layer.get(layer,np.empty((0,3,3)))
        # Centroid candidate lookup tolerates five-decimal scene serialization.
        # Full triangle vertex comparison then rules out same-center impostors.
        distance,indices=cKDTree(actual.mean(axis=1)).query(expected.mean(axis=1),k=min(12,len(actual)),workers=-1)
        errors=np.full(len(expected),np.inf)
        # Do not sort vertices by unrounded coordinates: scene serialization can
        # swap nearly equal coordinate ordering on otherwise identical faces.
        for start in range(0,len(expected),5000):
            end=min(start+5000,len(expected));candidates=actual[indices[start:end]]
            for order in permutations(range(3)):
                diff=np.abs(candidates[:,:,list(order),:]-expected[start:end,None,:,:])
                errors[start:end]=np.minimum(errors[start:end],diff.max(axis=(2,3)).min(axis=1))
        misses=int(np.count_nonzero(errors>2e-5))
        row={'layer':layer,'source_triangles':len(expected),'baked_triangles':len(actual),'unmatched_triangles':misses,
             'max_vertex_component_error_m':float(errors.max()),'counts_equal':len(expected)==len(actual)}
        collision_rows.append(row)
        if misses or len(expected)!=len(actual):all_preserved=False
    return {'status':'passed' if all_preserved else 'failed','tolerance_metres':.00002,
            'artifact_hashes':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in [manifest_path,output_path,scene_path]},
            'source_render_draw_calls':reference['counts']['renderables'],'retained_primitives':len(rows),
            'original_triangles':reference['counts']['render_triangles'],
            'active_source_input_triangles':manifest['source_mesh_triangles'],
            'output_triangles_in_actual_glb':output_triangles,
            'opaque_vertices_tested':source_vertices,'opaque_vertices_missing':vertex_missing,'opaque_vertex_max_error_m':max_error,
            'key_prop_draw_calls':keyword_report,'per_primitive_bounds':rows,
            'alpha_silhouette_changes':alpha_changes,
            'intentional_visual_changes':'Source alpha materials converted to coarse silhouettes, foliage QEM, removed minor surface stains/decals, non-render tools and verified atmospheric shader-effect sheets. Originally opaque prop, architecture, ground and canopy triangles retained.',
            'excluded_materials':manifest['omitted_nonvisible_or_surface_decals'],
            'excluded_shader_effects':effect_checks,
            'collision_layers':collision_rows,'collision_surface_counts':dict(surface_counts),
            'inactive_render_nodes_retained':disabled_render_leaks,
            'entity_activation_exclusions':{key:reference.get(key,[]) for key in ['runtime_disabled_brush_physics_nodes','runtime_never_solid_brush_physics_nodes','runtime_dynamic_nonsolid_physics_nodes','runtime_disabled_render_nodes']},
            'excluded_noncolliding_entities':dict(excluded),
            'excluded_trigger_entities':dict(Counter(r['name'] for r in reference['entity_physics'] if r['collision_policy']['role']=='trigger_or_metadata')),
            'discarded_degenerate_triangles':degenerate,
            'native_collision_chunks':len(shape_arrays)}


def audit_navigation():
    nav_path=ROOT/'assets/map/navigation.json';data_path=ROOT/'assets/map/map_data.json'
    if not nav_path.exists():return {'status':'awaiting_navigation'}
    nav=json.loads(nav_path.read_text(encoding='utf8'));data=json.loads(data_path.read_text(encoding='utf8'))
    points=np.asarray(nav['nodes']);edges=np.asarray(nav['edges'],dtype=int)
    lengths=np.linalg.norm(points[edges[:,0]]-points[edges[:,1]],axis=1)
    graph=coo_matrix((lengths,(edges[:,0],edges[:,1])),shape=(len(points),len(points))).tocsr()
    count,labels=connected_components(graph,directed=False);sizes=np.bincount(labels)
    tree=cKDTree(points)
    starts={team:tree.query(data['spawns'][team])[1] for team in ('CT','T')}
    ends={site:tree.query(data['sites'][site])[1] for site in ('A','B')}
    rows=[];all_routes=True
    for team,start in starts.items():
        distances=dijkstra(graph,directed=False,indices=start)
        for site,end in ends.items():
            connected=bool(labels[start]==labels[end]);all_routes&=connected
            rows.append({'team':team,'site':site,'connected':connected,
                         'start_node':int(start),'finish_node':int(end),
                         'path_length_m':round(float(distances[end]),3) if connected else None})
    spawn_routes=[]
    for team,spawns in data.get('spawn_points',{}).items():
        for index,spawn in enumerate(spawns):
            node=int(tree.query(spawn)[1])
            connected={site:bool(labels[node]==labels[end]) for site,end in ends.items()}
            all_routes&=all(connected.values())
            spawn_routes.append({'team':team,'spawn_index':index,'node_index':node,'connected_sites':connected})
    return {'status':'passed' if all_routes else 'failed','nodes':len(points),'edges':len(edges),
            'connected_components':int(count),'largest_component_sizes':sorted(sizes.tolist(),reverse=True)[:12],
            'main_routes':rows,'all_spawn_routes':spawn_routes,
            'source_navigation_sha256':hashlib.sha256(nav_path.read_bytes()).hexdigest(),
            'scope':'Graph connectivity only. Native character route traversal is validated separately; connectivity alone does not prove capsule clearance.'}


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--temp',type=Path,default=TEMP)
    parser.add_argument('--reference-only',action='store_true',help='Write source/state metadata before the next map bake; defer artifact audit')
    args=parser.parse_args()
    tmp=args.temp
    entities=read_entities(tmp/'entities/maps/de_mirage/entities/default_ents.vents')
    source_models=[]
    metadata=tmp/'reference_nodes/n0.txt'
    if metadata.exists():
        source_models=list(dict.fromkeys(re.findall(r'm_renderableModel = resource:"([^"]+)"',metadata.read_text())))
    by_stem={Path(s).stem:s for s in source_models}
    glb=GLB(tmp/'source_world.glb')
    renderables=[]
    for index,node in enumerate(glb.j['nodes']):
        name=node.get('name','')
        key=any(word in name.lower() for word in KEYWORDS)
        rec=bounds_record(glb,index,key)
        if rec is None:continue
        stem=name.split('.')[0]
        rec['source_model']=by_stem.get(stem,'')
        rec['baked_aggregate']=name.startswith('n0_lr0_agg_merge_')
        rec['prop_candidate']=key or not name.startswith('n0_lr0_')
        renderables.append(rec)
    entity_glb=GLB(tmp/'source_world_physics.glb')
    entity_physics=[]
    for index in range(len(entity_glb.j['nodes'])):
        rec=bounds_record(entity_glb,index,True)
        if rec:
            rec['collision_policy']=classify_collision(rec['name'],rec['extras'])
            entity_physics.append(rec)
    entity_states=apply_entity_states(entities,glb,entity_glb,renderables,entity_physics)
    world_glb=GLB(tmp/'world_solidphysics_physics.glb')
    world_physics=[]
    collision_components=[]
    for index in range(len(world_glb.j['nodes'])):
        rec=bounds_record(world_glb,index,False)
        if rec:
            rec['collision_policy']=classify_collision(rec['name'],rec['extras'])
            world_physics.append(rec)
            if rec['collision_policy']['role']=='solid_surface':
                for component_index,points in enumerate(world_glb.components(index)):
                    mn,mx=points.min(axis=0),points.max(axis=0)
                    center=(mn+mx)/2;size=mx-mn
                    if max(size)>30 or min(size)<.025:continue
                    item={'world_physics_node':index,'component_index':component_index,'surface':rec['extras'].get('SurfaceProperty'),
                          'bounds_min_godot':mn.round(5).tolist(),'bounds_max_godot':mx.round(5).tolist(),
                          'aabb_center_godot':center.round(5).tolist(),'aabb_extents_m':size.round(5).tolist(),
                          'aabb_center_source_units':game_to_source(center[None,:])[0].round(3).tolist()}
                    item.update(footprint(points))
                    collision_components.append(item)
    bombs={}
    bomb_entities=[e for e in entities if e.get('classname')=='func_bomb_target']
    bomb_shapes=[p for p in entity_physics if p['name']=='func_bomb_target']
    for entity,shape in zip(bomb_entities,bomb_shapes):
        site='A' if str(entity.get('bomb_site_designation'))=='0' else 'B'
        bombs[site]={'entity':entity,'region':shape}
    spawns={team:[e for e in entities if e.get('classname')==classname]
            for team,classname in [('CT','info_player_counterterrorist'),('T','info_player_terrorist')]}
    key_props=[r for r in renderables if any(k in r['name'] for k in KEYWORDS)]
    a_site_props=[r for r in key_props if -3<r['aabb_center_godot'][0]<32 and 18<r['aabb_center_godot'][2]<51 and -2<r['aabb_center_godot'][1]<14 and max(r['aabb_extents_m'])<15]
    audit=[]
    # Independent axis/scale check using an entity-origin and its node transform.
    for entity in entities:
        if entity.get('model')!='models/props_junk/plasticcrate01a.vmdl':continue
        expected=source_to_game(entity['origin'])
        candidates=[]
        for i,node in enumerate(glb.j['nodes']):
            if node.get('name','').startswith('plasticcrate01a.'):
                measured=glb_to_game(glb.matrix(i)[:3,3][None,:])[0]
                candidates.append((np.linalg.norm(measured-expected),i,measured))
        err,index,measured=min(candidates,key=lambda item:item[0])
        audit.append({'entity_index':entity['entity_index'],'glb_node':index,'expected_godot':expected.round(6).tolist(),'measured_godot':measured.round(6).tolist(),'error_m':float(err)})
    assert audit and max(a['error_m'] for a in audit)<.0001
    assert len(bombs)==2 and len(spawns['CT'])>=5 and len(spawns['T'])>=5
    output={'version':1,'source_game':'installed Counter-Strike 2 build 25218825',
            'source_vpk':r'E:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\game\csgo\maps\de_mirage.vpk',
            'source_units_metres':UNIT,'source_to_game':'[(sx+670)*.0254,(sz+256)*.0254,(-sy-847)*.0254]',
            'gltf_axis_evidence':'Source2Viewer GLB=(sourceY,sourceZ,sourceX)*.0254; verified on three independently dumped physics entities',
            'gltf_to_game':'[glbZ+17.018,glbY+6.5024,-glbX-21.5138]',
            'axis_validation':audit,
            'source_hashes':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in [tmp/'source_world.glb',tmp/'source_world_physics.glb',tmp/'world_solidphysics_physics.glb',metadata]},
            'counts':{'renderables':len(renderables),'render_triangles':sum(r['triangles'] for r in renderables),'prop_candidates':sum(r['prop_candidate'] for r in renderables),'key_prop_drawcalls':len(key_props),'entity_physics_shapes':len(entity_physics),'world_physics_groups':len(world_physics),'world_collision_triangles':sum(r['triangles'] for r in world_physics)},
            'renderables':renderables,'a_site_props':a_site_props,'entity_physics':entity_physics,
            'world_physics':world_physics,'prop_collision_components':collision_components,
            'a_site_cover_clusters':cover_clusters(collision_components),
            'a_site_collision_components':[r for r in collision_components if -13<r['aabb_center_godot'][0]<32 and 18<r['aabb_center_godot'][2]<51 and 1.8<r['aabb_center_godot'][1]<8],
            'bombsite_regions':bombs,'player_spawns':spawns,
            'entities_with_models':[e for e in entities if 'model' in e],
            'limitations':['AABB centers are geometric bounds centers, not artist pivots. Aggregate transforms are baked into indexed vertex positions.',
                           'Multiple source material draw calls can describe one prop. Do not instantiate each bounds record as a box.',
                           'Collision flags are retained; recommended vision treatment for grates/sky is a gameplay choice and does not duplicate all CS2 shader/penetration behavior.']}
    output.update(entity_states)
    output['baked_artifact_audit']={'status':'awaiting_baked_artifacts'} if args.reference_only else audit_baked_output(output,tmp)
    output['navigation_audit']={'status':'awaiting_navigation'} if args.reference_only else audit_navigation()
    dest=ROOT/'assets/map/source_props.json'
    dest.write_text(json.dumps(output,ensure_ascii=False,separators=(',',':')),encoding='utf8')
    print('SOURCE_MIRAGE_AUDIT',output['counts'])
    print('AXIS_MAX_ERROR_M',max(a['error_m'] for a in audit))
    for site,b in bombs.items():print('BOMBSITE',site,b['region']['bounds_min_godot'],b['region']['bounds_max_godot'])
    print('SPAWNS',{team:len(v) for team,v in spawns.items()})
    print('BAKED_AUDIT',{k:v for k,v in output['baked_artifact_audit'].items() if k not in ('per_primitive_bounds','excluded_materials','alpha_silhouette_changes')})
    print('NAVIGATION_AUDIT',{k:v for k,v in output['navigation_audit'].items() if k!='all_spawn_routes'})
    for r in a_site_props:
        if any(k in r['name'] for k in ('ammo_pallet','bomb_tank','shipping_crate','scaffold')):
            print('A_PROP',r['node_index'],r['name'],r['aabb_center_godot'],r['aabb_extents_m'])
    doc=['# Mirage 原版位置与碰撞校核','',
         '本次测量直接读取本机 CS2 build 25218825 的 de_mirage.vpk，经 Source 2 Viewer 20.0 导出世界、实体和独立 world_physics.vmdl。没有用 NAV 留白推测建筑或箱子的位置。',
         '',f"原始渲染网格：{len(renderables)} 个 draw call / {output['counts']['render_triangles']:,} 三角面。独立世界碰撞：{len(world_physics)} 个材质/碰撞分组，{output['counts']['world_collision_triangles']:,} 三角面；实体碰撞：{len(entity_physics)} 个形体。",'',
         '## 坐标与索引核验','',
         'Source → 本项目：`x=(sx+670)×0.0254; y=(sz+256)×0.0254; z=(-sy-847)×0.0254`。',
         'Source2Viewer 的 GLB 轴顺序为 `(Source Y, Source Z, Source X)`，已以 3 个独立实体的 origin 与 GLB node 变换交叉验证，最大误差 %.9f 米。'%(max(a['error_m'] for a in audit)),
         '一个 aggregate 的多个 draw call 共用 POSITION 顶点缓冲。每件物体的范围必须先按 indices 筛选实际引用的顶点；直接使用 accessor.min/max 会把单个箱子的范围错误扩展到整图。`source_props.json` 全部范围均按引用索引测量。',
         '', '## 安包区域','', '| 区域 | 最小坐标 x,y,z（米） | 最大坐标 x,y,z（米） |', '|---|---|---|']
    for site,b in bombs.items():doc.append(f"| {site} | {b['region']['bounds_min_godot']} | {b['region']['bounds_max_godot']} |")
    doc+=['','完整安包多边形、各出生点 origin/angles/enabled/priority 已保存在 `source_props.json`。出生点统计：'+str({k:len(v) for k,v in spawns.items()})+'。安包触发体不是实心墙。',
          '', '## A 点关键物体的源网格范围','', '| 节点 | 源模型分组 | 中心 x,y,z（米） | 范围 x,y,z（米） |', '|---|---|---|---|']
    for r in a_site_props:
        if any(k in r['name'] for k in ('ammo_pallet','bomb_tank','shipping_crate','scaffold')):
            doc.append(f"| {r['node_index']} | {r['name'].replace('n0_lr0_agg_merge_','')} | {np.round(r['aabb_center_godot'],3).tolist()} | {np.round(r['aabb_extents_m'],3).tolist()} |")
    doc+=['','这些记录是源材质 draw call 的真实范围，不代表每个 draw call 是一整只箱子，也不是建议生成的盒式障碍物。最终地图应保留这些网格的变换和整体轮廓，进行受控简化与重新绘色。',
          '', '## 碰撞分类','',
          '实体中的 func_bomb_target、func_buyzone、env_cs_place、post_processing_volume 和 func_nav_markup 是触发/元数据体，禁止作为全实心碰撞。playerclip/npcclip 用于人物阻挡，不能同时作为遮视野与挡弹墙；csgo_grenadeclip 只用于投掷物。passbullets 标志需要独立保留。每个世界和实体形体的原始 SurfaceProperty、InteractAs 与建议用途均保存在 JSON。',
          '', '依据：[Source 2 Viewer 命令行文档](https://s2v.app/ValveResourceFormat/guides/command-line.html)、[地图导出说明](https://s2v.app/ValveResourceFormat/guides/exporting-maps.html)。工具解析基于逆向格式；本报告验证几何位置、范围和标志，不声称完整还原 Source 2 的全部渲染与穿透规则。','']
    doc+=['## 实体启用状态','',
          '仅保留每个导出模型的三角面还不够：必须同时读取 CS2 实体数据中的 StartDisabled、solidity、solid。原版 Mirage 包含 retake 模式专用封路体，普通爆破模式初始禁用；忽略这一状态会在 A/B 出入口生成不该出现的墙。',
          f"按源实体类别与三维 origin 匹配物理节点，最大位置匹配误差 {max(s['origin_match_error_m'] for s in entity_states['runtime_entity_state']):.9f} 米。明确排除 29 个 startdisabled 的 retake func_brush、6 个仍显示但 solidity=1（Never Solid）的 func_brush，另有 3 个 solid=0 的动态道具物理形体（布帘与两个尚未启用的破损百叶窗残余模型）。共 38 个物理形体、928 个面不参与普通模式碰撞；17 个初始禁用的渲染节点也不显示。",
          '原始状态、实体编号、模型路径、匹配误差及各排除节点清单全部保存于 JSON。物理模型仍保留在源记录中，以便审计，未移动地图物体。普通爆破中有效的可破坏金属封板保持启用；破坏后状态需由游戏交互单独处理。',
          '枚举与启停行为可参考 Valve 的公开 [CFuncBrush 定义](https://github.com/ValveSoftware/source-sdk-2013/blob/master/src/game/server/modelentities.h) 与 [实现](https://github.com/ValveSoftware/source-sdk-2013/blob/master/src/game/server/modelentities.cpp)；本图启用状态和数值本身来自当前 CS2 实体导出，而非旧游戏地图。','']
    result=output['baked_artifact_audit']
    if result['status']!='awaiting_baked_artifacts':
        doc+=['## 最终文件的独立核验','',
              f"校核状态：**{result['status']}**。直接重新读取最终 `source_environment.glb` 和 `mirage_baked.tscn`，不是只信任生成器记录的范围。保留 {result['retained_primitives']:,} 个材质绘制单元，实际导出 {result['output_triangles_in_actual_glb']:,} 个三角面。",
              f"源材质明确标为 OPAQUE 的建筑、地面、道具与金属道具，其 {result['opaque_vertices_tested']:,} 个原始引用顶点全部逐点查询；20 微米容差内缺失 {result['opaque_vertices_missing']} 个，最大偏差 {result['opaque_vertex_max_error_m']:.9f} 米。该类三角面数量也保持不变。每个源节点/primitive 的源与输出范围、中心偏差保存在 JSON 中。",
              '', '| 源模型分组 | 源 draw call / 保留 | 源三角面 / 导出 |', '|---|---|---|']
        for key,value in result['key_prop_draw_calls'].items():
            doc.append(f"| {key} | {value['source_draw_calls']} / {value['retained_draw_calls']} | {value['source_triangles']} / {value['output_triangles']} |")
        doc+=['','A 点西侧/默认安包附近的弹药托盘、罐架、后侧木箱、Tetris 一带石箱以及票亭方向罐架，使用源三角网格原位保留。下表按物理壳相邻足迹分组，便于肉眼对照；不是新建碰撞盒，亦不把非官方组名当作源模型名称。','',
              '| 物理表面组成 | 原位中心 x,y,z（米） | 整组范围 x,y,z（米） |','|---|---|---|']
        for cluster in output['a_site_cover_clusters']:
            doc.append('| '+str(cluster.get('surfaces',cluster.get('surface_counts','')))+' | '+str(np.round(cluster['aabb_center_godot'],3).tolist())+' | '+str(np.round(cluster['aabb_extents_m'],3).tolist())+' |')
        doc+=['','碰撞校核按源标志分别比较原始与最终文件中的每个三角形；会先筛掉原文件退化面，再以三顶点逐一匹配，容差 20 微米。','',
              '| Godot layer | 源面数 | 最终面数 | 未匹配 | 最大坐标偏差（米） |','|---|---|---|---|---|']
        for row in result['collision_layers']:
            doc.append(f"| {row['layer']} | {row['source_triangles']:,} | {row['baked_triangles']:,} | {row['unmatched_triangles']} | {row['max_vertex_component_error_m']:.9f} |")
        doc+=['',f"最终 {result['native_collision_chunks']} 个空间分块；排除退化面 {result['discarded_degenerate_triangles']} 个。排除触发/元数据实体：`{result['excluded_trigger_entities']}`。",'',
              f"风格化修改范围：重绘材质颜色、轻微面色变化、源 MASK/BLEND 材质提取粗略透明轮廓（{len(result['alpha_silhouette_changes'])} 个材质绘制单元，含植被、栅栏、灯、门等）、植被减面；省略细小污渍/贴花和仅供引擎使用的工具表面。源 OPAQUE 建筑、地面和道具保持三角几何，未手动挪动 A 点障碍物。",
              '保留源外观几何与碰撞不代表照搬 Source 2 光照引擎、贴图精度或破坏/物理交互。此报告确认的是比例、位置、拓扑和碰撞类别；照明表现与操控仍需在项目内单独检查。','']
        doc += [f"明确排除并独立核验的飘尘特效：{len(result['excluded_shader_effects'])} 个绘制单元、{sum(e['source_triangles'] for e in result['excluded_shader_effects'])} 个面。源材质 `materials/effects/smoke/dust_002.vmat` 使用 `csgo_effects.vfx`、动画透明遮罩、深度羽化及不投影标志；导出器漏写 alphaMode 时不能把这些片面当作不透明建筑。逐节点源材质验证结果保存在 JSON 的 `excluded_shader_effects`，它们没有进入碰撞。",'B 点棚布移动到独立 Canopy 视觉组以支持局部剖切；源顶点与 5,424 个三角面全部保留，并纳入同一逐点位置审计。','']
    nav_result=output['navigation_audit']
    if nav_result['status']!='awaiting_navigation':
        doc+=['## 导航连接性','',f"状态：**{nav_result['status']}**。{nav_result['nodes']:,} 个节点、{nav_result['edges']:,} 条边，{nav_result['connected_components']} 个连通分量。检查两个阵营至 A/B 的四条主路线及所有 {len(nav_result['all_spawn_routes'])} 个出生点至两个包点的连接。",'',
              '| 路线 | 连通 | 图上最短距离（米） |','|---|---|---|']
        for row in nav_result['main_routes']:doc.append(f"| {row['team']} → {row['site']} | {row['connected']} | {row['path_length_m']} |")
        doc+=['','这是图连接检查；胶囊体能否实际通过、台阶处理和跟随航点须使用游戏原生物理进一步验证，不能把非空寻路结果当作实际行走通过。','']
    (ROOT/'docs/placement-audit.md').write_text('\n'.join(doc),encoding='utf8')
    if result['status']=='failed' or nav_result['status']=='failed':
        raise SystemExit('Baked Mirage artifact/navigation audit failed; see assets/map/source_props.json and docs/placement-audit.md')


if __name__=='__main__':main()
